# Lab01
Sreyrath Poeun
02/04/2023

In [21]:
formula_string = 'Capital Asset Pricing Model' 

In [22]:
#Part 4 ?
fv=150
r=.05
t=2
pv=fv/(1+r)**t
print("Present Value: $%.2f" % pv)

Present Value: $136.05


In [23]:
#Part 5: Create list
stock= ["Apple Inc.", "AAPL", 172.39]
stock[1]

'AAPL'

In [24]:
#Part 6 if, elif, else
StockPercentile=110


In [25]:
if StockPercentile>=90:
    print("Add this stock to buy list")

Add this stock to buy list


In [26]:
if StockPercentile>=90:
    print("Add this stock to buy list")
else:
    print("Exclude stock")

Add this stock to buy list


In [27]:
if StockPercentile>100:
    print("Check calculations")
elif StockPercentile>=90:
    print("Add this stock to buy list")
else:
    print("Exclude stock")

Check calculations


In [28]:
#Part 7 while loop
i=10
while i>=1:
    i=i-1
    print("counting down...%d"%i)

print("Blastoff!")


counting down...9
counting down...8
counting down...7
counting down...6
counting down...5
counting down...4
counting down...3
counting down...2
counting down...1
counting down...0
Blastoff!


In [29]:
#Part 8 Arrays
import numpy as np 

a=np.arange(5,101,5)
print(a[0])
a[9]


5


50

In [30]:
b=a**2
type(b)

numpy.ndarray

In [31]:
#Part 9 Multiple Dim arrays
c=np.eye(4)
print("Size:"+str(np.size(c)))
print("Dim:" + str(np.ndim(c)))
print("Shape:"+ str(np.shape(c)))
type(c)

Size:16
Dim:2
Shape:(4, 4)


numpy.ndarray

In [32]:
c*3

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [33]:
#Print the element in the 2nd row and 2nd column
c[1][1]

# I get "1" since I never store the c*3 array.

1.0

In [34]:
#print 2nd col
c[:,1]

array([0., 1., 0., 0.])

In [35]:
#Print the first two columns of the array
c[:,:2]

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [36]:
# Print the first two columns of the array
c[:,:2]

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [37]:
#Print a portion of the array
c[:2,1:3]

array([[0., 0.],
       [1., 0.]])

In [38]:
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])